var g_cut= false;
var g_mousedown=false;
var g_downX=0;
var g_downY=0;
var g_imgPath="../src/411/";
var g_imgName="";
var newWindow;
var g_pageIdx="page0009";
var g_ui ="";
var g_offsetx=0;
var g_offsety=0;
var g_css=[];